version: "3"
services:
  db: 
    image: postgres:12.3
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=dbuser
    - POSTGRES_PASSWORD=dbpass
  db-migrate:
    image: migrate/migrate
    volumes:
    - ./dynamic/storage/postgres/migrations:/migrations
    restart: on-failure
    depends_on:
    - db
    command: "-path=/migrations -database postgres://dbuser:dbpass@db:5432/dbuser?sslmode=disable up"
  backend:
    restart: on-failure
    build: 
      context: dynamic
      dockerfile: docker/Dockerfile
    ports:
    - "8080:80"
  frontend:
    build:
      context: static
      dockerfile: docker/Dockerfile
    ports:
    - "8081:80"
