version: "3"
services:
  db: 
    build:
      context: dynamic
      dockerfile: docker/Dockerfile.postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
        #  db-migrate:
    #    image: migrate/migrate
    #    volumes:
    #      - ./dynamic/storage/postgres/migrations:/migrations
    #    restart: on-failure
    #    depends_on:
    #      - db
    #    command: "-path=/migrations -database postgres://dbuser:dbpass@db:5432/dbuser?sslmode=disable up"
  backend:
    restart: on-failure
    build: 
      context: dynamic
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    environment:
      - DSS_FRONTEND=http://localhost:8081
      - DSS_POSTGRESURL=postgres://dbuser:dbpass@db:5432/dbuser?sslmode=disable
      - DSS_ENVIRONMENT=development
      - DSS_SQUAREKEY
      - DSS_MAILKEY
      - DSS_PORT=80
  frontend:
    build:
      context: static
      dockerfile: docker/Dockerfile
      args:
        - HUGO_BASEURL=http://localhost:8081
        - HUGO_DYNAMIC=http://localhost:8080
    ports:
      - "8081:80"
