version: "3"
services:
  frontend:
    build:
      context: static
      dockerfile: docker/Dockerfile
      args:
        - HUGO_BASEURL=https://dayton-swing-smackdown-testing.netlify.app
        - HUGO_DYNAMIC=https://dayton-swing-smackdown-testing.herokuapp.com
  backend:
    build: 
      context: dynamic
      dockerfile: docker/Dockerfile
