version: "3"
services:
  db: 
    build:
      context: dynamic
      dockerfile: docker/Dockerfile.postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
  test_db: 
    build:
      context: dynamic
      dockerfile: docker/Dockerfile.postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
  backend:
    build: 
      context: dynamic
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    environment:
      - DSS_VERSION=local
      - DSS_FRONTEND=http://localhost:8081
      - DSS_POSTGRESURL=postgres://dbuser:dbpass@db:5432/dbuser?sslmode=disable
      - DSS_TEST_POSTGRESURL=postgres://dbuser:dbpass@test_db:5432/dbuser?sslmode=disable
      - DSS_ENVIRONMENT=development
      - DSS_AUTH0ENDPOINT
      - DSS_SQUAREKEY
      - DSS_MAILKEY
      - DSS_RECAPTCHAKEY
      - DSS_PORT=80
    volumes:
      - "./dynamic/:/app:ro"
  frontend:
    build:
      context: static
      dockerfile: docker/Dockerfile
    environment:
      - GATSBY_BACKEND=http://localhost:8080
      - GATSBY_FRONTEND=http://localhost:8081
      - GATSBY_CLIENT_ID
      - GATSBY_AUTH0_DOMAIN
      - GATSBY_AUTH0_AUDIENCE
      - GATSBY_VERSION=local
    volumes:
      - "./static/src:/app/src:ro"
      - "./static/static:/app/static:ro"
    ports:
      - "8081:8000"
