// Code generated by protoc-gen-twirp v5.10.0, DO NOT EDIT.
// source: rpc/dss/discount.proto

package dss

import bytes "bytes"
import strings "strings"
import context "context"
import fmt "fmt"
import ioutil "io/ioutil"
import http "net/http"
import strconv "strconv"

import jsonpb "github.com/golang/protobuf/jsonpb"
import proto "github.com/golang/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// ==================
// Discount Interface
// ==================

type Discount interface {
	Add(context.Context, *DiscountAddReq) (*DiscountAddRes, error)

	Get(context.Context, *DiscountGetReq) (*DiscountGetRes, error)
}

// ========================
// Discount Protobuf Client
// ========================

type discountProtobufClient struct {
	client HTTPClient
	urls   [2]string
	opts   twirp.ClientOptions
}

// NewDiscountProtobufClient creates a Protobuf client that implements the Discount interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewDiscountProtobufClient(addr string, client HTTPClient, opts ...twirp.ClientOption) Discount {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	prefix := urlBase(addr) + DiscountPathPrefix
	urls := [2]string{
		prefix + "Add",
		prefix + "Get",
	}

	return &discountProtobufClient{
		client: client,
		urls:   urls,
		opts:   clientOpts,
	}
}

func (c *discountProtobufClient) Add(ctx context.Context, in *DiscountAddReq) (*DiscountAddRes, error) {
	ctx = ctxsetters.WithPackageName(ctx, "dss")
	ctx = ctxsetters.WithServiceName(ctx, "Discount")
	ctx = ctxsetters.WithMethodName(ctx, "Add")
	out := new(DiscountAddRes)
	err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *discountProtobufClient) Get(ctx context.Context, in *DiscountGetReq) (*DiscountGetRes, error) {
	ctx = ctxsetters.WithPackageName(ctx, "dss")
	ctx = ctxsetters.WithServiceName(ctx, "Discount")
	ctx = ctxsetters.WithMethodName(ctx, "Get")
	out := new(DiscountGetRes)
	err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ====================
// Discount JSON Client
// ====================

type discountJSONClient struct {
	client HTTPClient
	urls   [2]string
	opts   twirp.ClientOptions
}

// NewDiscountJSONClient creates a JSON client that implements the Discount interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewDiscountJSONClient(addr string, client HTTPClient, opts ...twirp.ClientOption) Discount {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	prefix := urlBase(addr) + DiscountPathPrefix
	urls := [2]string{
		prefix + "Add",
		prefix + "Get",
	}

	return &discountJSONClient{
		client: client,
		urls:   urls,
		opts:   clientOpts,
	}
}

func (c *discountJSONClient) Add(ctx context.Context, in *DiscountAddReq) (*DiscountAddRes, error) {
	ctx = ctxsetters.WithPackageName(ctx, "dss")
	ctx = ctxsetters.WithServiceName(ctx, "Discount")
	ctx = ctxsetters.WithMethodName(ctx, "Add")
	out := new(DiscountAddRes)
	err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *discountJSONClient) Get(ctx context.Context, in *DiscountGetReq) (*DiscountGetRes, error) {
	ctx = ctxsetters.WithPackageName(ctx, "dss")
	ctx = ctxsetters.WithServiceName(ctx, "Discount")
	ctx = ctxsetters.WithMethodName(ctx, "Get")
	out := new(DiscountGetRes)
	err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// =======================
// Discount Server Handler
// =======================

type discountServer struct {
	Discount
	hooks *twirp.ServerHooks
}

func NewDiscountServer(svc Discount, hooks *twirp.ServerHooks) TwirpServer {
	return &discountServer{
		Discount: svc,
		hooks:    hooks,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *discountServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// DiscountPathPrefix is used for all URL paths on a twirp Discount server.
// Requests are always: POST DiscountPathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const DiscountPathPrefix = "/twirp/dss.Discount/"

func (s *discountServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "dss")
	ctx = ctxsetters.WithServiceName(ctx, "Discount")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}

	switch req.URL.Path {
	case "/twirp/dss.Discount/Add":
		s.serveAdd(ctx, resp, req)
		return
	case "/twirp/dss.Discount/Get":
		s.serveGet(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}
}

func (s *discountServer) serveAdd(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveAddJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveAddProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *discountServer) serveAddJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Add")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(DiscountAddReq)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the json request could not be decoded"))
		return
	}

	// Call service method
	var respContent *DiscountAddRes
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = s.Discount.Add(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *DiscountAddRes and nil error while calling Add. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	respBytes := buf.Bytes()
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *discountServer) serveAddProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Add")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to read request body"))
		return
	}
	reqContent := new(DiscountAddReq)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	// Call service method
	var respContent *DiscountAddRes
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = s.Discount.Add(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *DiscountAddRes and nil error while calling Add. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *discountServer) serveGet(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *discountServer) serveGetJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Get")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(DiscountGetReq)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the json request could not be decoded"))
		return
	}

	// Call service method
	var respContent *DiscountGetRes
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = s.Discount.Get(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *DiscountGetRes and nil error while calling Get. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	respBytes := buf.Bytes()
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *discountServer) serveGetProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Get")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to read request body"))
		return
	}
	reqContent := new(DiscountGetReq)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	// Call service method
	var respContent *DiscountGetRes
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = s.Discount.Get(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *DiscountGetRes and nil error while calling Get. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *discountServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor1, 0
}

func (s *discountServer) ProtocGenTwirpVersion() string {
	return "v5.10.0"
}

func (s *discountServer) PathPrefix() string {
	return DiscountPathPrefix
}

var twirpFileDescriptor1 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x6b, 0x83, 0x40,
	0x10, 0x8d, 0xb1, 0x24, 0x3a, 0x85, 0x50, 0xb6, 0x50, 0x16, 0x4f, 0x22, 0x3d, 0x08, 0x05, 0xa5,
	0xe9, 0xb9, 0x87, 0x48, 0x21, 0x39, 0xb6, 0xdb, 0x43, 0xa1, 0x37, 0xe3, 0x2c, 0x25, 0x60, 0xd4,
	0x3a, 0x9b, 0xff, 0x5f, 0x76, 0xe3, 0x6a, 0x22, 0x5e, 0x7a, 0x91, 0xf5, 0xf1, 0xbe, 0x66, 0x18,
	0x78, 0x68, 0x9b, 0x22, 0x45, 0xa2, 0x14, 0x0f, 0x54, 0xd4, 0xa7, 0x4a, 0x25, 0x4d, 0x5b, 0xab,
	0x9a, 0xb9, 0x48, 0x14, 0xbd, 0xc3, 0xea, 0xad, 0x83, 0x37, 0x47, 0xfd, 0x65, 0x1c, 0x16, 0x58,
	0x97, 0x65, 0xde, 0x72, 0x2f, 0x74, 0x62, 0x77, 0x37, 0x13, 0xdd, 0x3f, 0x0b, 0x60, 0xd9, 0xc8,
	0xb6, 0x90, 0x95, 0xe2, 0x7e, 0xe8, 0xc4, 0xfe, 0x6e, 0x26, 0x2c, 0x90, 0x79, 0xb0, 0xc8, 0x8d,
	0x3e, 0xfa, 0x80, 0xd5, 0xe7, 0xa1, 0xfa, 0x29, 0xa5, 0xf5, 0x65, 0x0c, 0x6e, 0xaa, 0xfc, 0x28,
	0xb9, 0xa3, 0x45, 0xc2, 0xbc, 0xd9, 0x93, 0xe5, 0xf3, 0x79, 0xe8, 0xc4, 0xb7, 0xeb, 0xfb, 0x04,
	0x89, 0x92, 0xeb, 0x2a, 0xc2, 0x5a, 0x7e, 0x0d, 0x25, 0xb3, 0x53, 0x85, 0xa5, 0xd4, 0x96, 0x45,
	0x8d, 0xbd, 0xa5, 0x7e, 0xb3, 0x67, 0xf0, 0xed, 0x84, 0xc4, 0xe7, 0xa1, 0xdb, 0xbb, 0x5e, 0xd7,
	0x11, 0x03, 0x2b, 0x7a, 0xbd, 0x98, 0x1e, 0x51, 0xc8, 0x5f, 0xdd, 0x6b, 0x6f, 0x22, 0x8c, 0xf5,
	0xb8, 0xd7, 0x39, 0x5d, 0x74, 0x94, 0xe8, 0x6e, 0x24, 0xa7, 0xe8, 0x71, 0x40, 0xb6, 0x52, 0x69,
	0xc3, 0x89, 0xa6, 0x97, 0xb1, 0x86, 0x45, 0xff, 0x8a, 0x5d, 0x97, 0xe0, 0xf5, 0xbb, 0x4d, 0xc1,
	0xdd, 0x20, 0xb2, 0xd1, 0xfa, 0xcc, 0x2c, 0xc1, 0x04, 0x48, 0x5a, 0xb0, 0x95, 0x6a, 0x24, 0x38,
	0x77, 0x0d, 0x26, 0x40, 0xca, 0xfc, 0xef, 0x65, 0x77, 0x40, 0xfb, 0x85, 0x39, 0x9c, 0x97, 0xbf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x94, 0x49, 0x54, 0x49, 0x52, 0x02, 0x00, 0x00,
}
