// Code generated by protoc-gen-twirp v8.1.0, DO NOT EDIT.
// source: forms.proto

package dss

import context "context"
import fmt "fmt"
import http "net/http"
import ioutil "io/ioutil"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// ===============
// Forms Interface
// ===============

type Forms interface {
	ContactUs(context.Context, *ContactUsReq) (*ContactUsRes, error)

	SafetyReport(context.Context, *SafetyReportReq) (*SafetyReportRes, error)
}

// =====================
// Forms Protobuf Client
// =====================

type formsProtobufClient struct {
	client      HTTPClient
	urls        [2]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewFormsProtobufClient creates a Protobuf client that implements the Forms interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewFormsProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) Forms {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "dss", "Forms")
	urls := [2]string{
		serviceURL + "ContactUs",
		serviceURL + "SafetyReport",
	}

	return &formsProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *formsProtobufClient) ContactUs(ctx context.Context, in *ContactUsReq) (*ContactUsRes, error) {
	ctx = ctxsetters.WithPackageName(ctx, "dss")
	ctx = ctxsetters.WithServiceName(ctx, "Forms")
	ctx = ctxsetters.WithMethodName(ctx, "ContactUs")
	caller := c.callContactUs
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ContactUsReq) (*ContactUsRes, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ContactUsReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ContactUsReq) when calling interceptor")
					}
					return c.callContactUs(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ContactUsRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ContactUsRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *formsProtobufClient) callContactUs(ctx context.Context, in *ContactUsReq) (*ContactUsRes, error) {
	out := new(ContactUsRes)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *formsProtobufClient) SafetyReport(ctx context.Context, in *SafetyReportReq) (*SafetyReportRes, error) {
	ctx = ctxsetters.WithPackageName(ctx, "dss")
	ctx = ctxsetters.WithServiceName(ctx, "Forms")
	ctx = ctxsetters.WithMethodName(ctx, "SafetyReport")
	caller := c.callSafetyReport
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *SafetyReportReq) (*SafetyReportRes, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SafetyReportReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SafetyReportReq) when calling interceptor")
					}
					return c.callSafetyReport(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SafetyReportRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SafetyReportRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *formsProtobufClient) callSafetyReport(ctx context.Context, in *SafetyReportReq) (*SafetyReportRes, error) {
	out := new(SafetyReportRes)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// =================
// Forms JSON Client
// =================

type formsJSONClient struct {
	client      HTTPClient
	urls        [2]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewFormsJSONClient creates a JSON client that implements the Forms interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewFormsJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) Forms {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "dss", "Forms")
	urls := [2]string{
		serviceURL + "ContactUs",
		serviceURL + "SafetyReport",
	}

	return &formsJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *formsJSONClient) ContactUs(ctx context.Context, in *ContactUsReq) (*ContactUsRes, error) {
	ctx = ctxsetters.WithPackageName(ctx, "dss")
	ctx = ctxsetters.WithServiceName(ctx, "Forms")
	ctx = ctxsetters.WithMethodName(ctx, "ContactUs")
	caller := c.callContactUs
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ContactUsReq) (*ContactUsRes, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ContactUsReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ContactUsReq) when calling interceptor")
					}
					return c.callContactUs(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ContactUsRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ContactUsRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *formsJSONClient) callContactUs(ctx context.Context, in *ContactUsReq) (*ContactUsRes, error) {
	out := new(ContactUsRes)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *formsJSONClient) SafetyReport(ctx context.Context, in *SafetyReportReq) (*SafetyReportRes, error) {
	ctx = ctxsetters.WithPackageName(ctx, "dss")
	ctx = ctxsetters.WithServiceName(ctx, "Forms")
	ctx = ctxsetters.WithMethodName(ctx, "SafetyReport")
	caller := c.callSafetyReport
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *SafetyReportReq) (*SafetyReportRes, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SafetyReportReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SafetyReportReq) when calling interceptor")
					}
					return c.callSafetyReport(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SafetyReportRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SafetyReportRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *formsJSONClient) callSafetyReport(ctx context.Context, in *SafetyReportReq) (*SafetyReportRes, error) {
	out := new(SafetyReportRes)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ====================
// Forms Server Handler
// ====================

type formsServer struct {
	Forms
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewFormsServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewFormsServer(svc Forms, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &formsServer{
		Forms:            svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *formsServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *formsServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// FormsPathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const FormsPathPrefix = "/twirp/dss.Forms/"

func (s *formsServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "dss")
	ctx = ctxsetters.WithServiceName(ctx, "Forms")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "dss.Forms" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "ContactUs":
		s.serveContactUs(ctx, resp, req)
		return
	case "SafetyReport":
		s.serveSafetyReport(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *formsServer) serveContactUs(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveContactUsJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveContactUsProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *formsServer) serveContactUsJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ContactUs")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(ContactUsReq)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.Forms.ContactUs
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ContactUsReq) (*ContactUsRes, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ContactUsReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ContactUsReq) when calling interceptor")
					}
					return s.Forms.ContactUs(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ContactUsRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ContactUsRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ContactUsRes
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ContactUsRes and nil error while calling ContactUs. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *formsServer) serveContactUsProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ContactUs")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(ContactUsReq)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.Forms.ContactUs
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ContactUsReq) (*ContactUsRes, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ContactUsReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ContactUsReq) when calling interceptor")
					}
					return s.Forms.ContactUs(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ContactUsRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ContactUsRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ContactUsRes
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ContactUsRes and nil error while calling ContactUs. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *formsServer) serveSafetyReport(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveSafetyReportJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveSafetyReportProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *formsServer) serveSafetyReportJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "SafetyReport")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(SafetyReportReq)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.Forms.SafetyReport
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *SafetyReportReq) (*SafetyReportRes, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SafetyReportReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SafetyReportReq) when calling interceptor")
					}
					return s.Forms.SafetyReport(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SafetyReportRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SafetyReportRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *SafetyReportRes
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *SafetyReportRes and nil error while calling SafetyReport. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *formsServer) serveSafetyReportProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "SafetyReport")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(SafetyReportReq)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.Forms.SafetyReport
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *SafetyReportReq) (*SafetyReportRes, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SafetyReportReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SafetyReportReq) when calling interceptor")
					}
					return s.Forms.SafetyReport(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SafetyReportRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SafetyReportRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *SafetyReportRes
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *SafetyReportRes and nil error while calling SafetyReport. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *formsServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor2, 0
}

func (s *formsServer) ProtocGenTwirpVersion() string {
	return "v8.1.0"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *formsServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "dss", "Forms")
}

var twirpFileDescriptor2 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4b, 0x6f, 0xe2, 0x30,
	0x14, 0x85, 0xc5, 0x23, 0x40, 0x6e, 0x32, 0x0f, 0x2c, 0x16, 0x51, 0x16, 0x33, 0x0c, 0xb3, 0x99,
	0xcd, 0x04, 0x95, 0xee, 0xda, 0x1d, 0x95, 0xba, 0x6c, 0xa5, 0xb4, 0xdd, 0x74, 0x13, 0xe5, 0x71,
	0x03, 0x91, 0x88, 0xed, 0xfa, 0x3a, 0x48, 0xfc, 0xc8, 0xfe, 0xa7, 0x0a, 0x07, 0xa2, 0x94, 0xc2,
	0xce, 0xfe, 0x7c, 0xe4, 0x7b, 0xce, 0xb1, 0xc1, 0xc9, 0x85, 0x2a, 0x29, 0x90, 0x4a, 0x68, 0xc1,
	0x7a, 0x19, 0x91, 0xff, 0x7b, 0x25, 0xc4, 0x6a, 0x83, 0x73, 0x83, 0x92, 0x2a, 0x9f, 0xeb, 0xa2,
	0x44, 0xd2, 0x71, 0x29, 0x6b, 0xd5, 0x6c, 0x07, 0xee, 0x9d, 0xe0, 0x3a, 0x4e, 0xf5, 0x0b, 0x85,
	0xf8, 0xc6, 0x18, 0xf4, 0x79, 0x5c, 0xa2, 0xd7, 0x99, 0x76, 0xfe, 0xd9, 0xa1, 0x59, 0xb3, 0x09,
	0x58, 0x58, 0xc6, 0xc5, 0xc6, 0xeb, 0x1a, 0x58, 0x6f, 0xd8, 0x4f, 0xe8, 0x95, 0xb4, 0xf2, 0x7a,
	0x86, 0xed, 0x97, 0xec, 0x3f, 0x30, 0x85, 0x69, 0x2c, 0x75, 0xba, 0x8e, 0x23, 0x85, 0x24, 0x05,
	0x27, 0xf4, 0xfa, 0x46, 0x30, 0x6e, 0x4e, 0xc2, 0xc3, 0xc1, 0xec, 0xfb, 0xa7, 0xd1, 0x34, 0x7b,
	0xef, 0xc2, 0x8f, 0xa7, 0x38, 0x47, 0xbd, 0x0b, 0x51, 0x0a, 0xa5, 0xf7, 0x76, 0x6e, 0xc1, 0x11,
	0x69, 0x5a, 0x29, 0x85, 0x59, 0x24, 0xb8, 0x71, 0xe5, 0x2c, 0xfc, 0xa0, 0x4e, 0x15, 0x1c, 0x53,
	0x05, 0xcf, 0xc7, 0x54, 0x21, 0x1c, 0xe5, 0x8f, 0x9c, 0x4d, 0xc1, 0xc9, 0x90, 0x52, 0x55, 0x48,
	0x5d, 0x08, 0x7e, 0x70, 0xdf, 0x46, 0xcc, 0x87, 0x11, 0xe1, 0x16, 0x55, 0xa1, 0x77, 0x26, 0x88,
	0x15, 0x36, 0x7b, 0xf6, 0x17, 0xbe, 0x15, 0x44, 0x15, 0x52, 0x94, 0x60, 0x2e, 0x54, 0x1d, 0x64,
	0x14, 0xba, 0x35, 0x5c, 0x1a, 0xc6, 0x7e, 0x01, 0x28, 0x24, 0xb1, 0xa9, 0xcc, 0x04, 0xcb, 0x4c,
	0x68, 0x91, 0xa6, 0xce, 0xc1, 0xb9, 0x3a, 0x87, 0xed, 0x3a, 0xff, 0x80, 0x2b, 0xd7, 0x82, 0x63,
	0xc4, 0xab, 0x32, 0x41, 0xe5, 0x8d, 0x6a, 0xb7, 0x86, 0x3d, 0x18, 0x74, 0xa1, 0x5f, 0xfb, 0x52,
	0xbf, 0xe3, 0xd3, 0x3a, 0x69, 0xb1, 0x05, 0xeb, 0x7e, 0xff, 0x45, 0xd8, 0x15, 0xd8, 0x4d, 0xf7,
	0x6c, 0x1c, 0x64, 0x44, 0x41, 0xfb, 0x1b, 0xf8, 0x5f, 0x10, 0xb1, 0x1b, 0x70, 0xdb, 0xd7, 0xb1,
	0x89, 0x91, 0x9c, 0x3c, 0x98, 0x7f, 0x8e, 0xd2, 0xd2, 0x7e, 0x1d, 0x2a, 0x99, 0xce, 0x33, 0xa2,
	0x64, 0x60, 0x1e, 0xed, 0xfa, 0x23, 0x00, 0x00, 0xff, 0xff, 0x35, 0xbc, 0x45, 0x84, 0xac, 0x02,
	0x00, 0x00,
}
