// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: forms.proto

package dss

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContactUsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name              string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email             string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Msg               string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	RecaptchaResponse string `protobuf:"bytes,4,opt,name=recaptcha_response,json=recaptchaResponse,proto3" json:"recaptcha_response,omitempty"`
}

func (x *ContactUsReq) Reset() {
	*x = ContactUsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactUsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactUsReq) ProtoMessage() {}

func (x *ContactUsReq) ProtoReflect() protoreflect.Message {
	mi := &file_forms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactUsReq.ProtoReflect.Descriptor instead.
func (*ContactUsReq) Descriptor() ([]byte, []int) {
	return file_forms_proto_rawDescGZIP(), []int{0}
}

func (x *ContactUsReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContactUsReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ContactUsReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ContactUsReq) GetRecaptchaResponse() string {
	if x != nil {
		return x.RecaptchaResponse
	}
	return ""
}

type ContactUsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ContactUsRes) Reset() {
	*x = ContactUsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactUsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactUsRes) ProtoMessage() {}

func (x *ContactUsRes) ProtoReflect() protoreflect.Message {
	mi := &file_forms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactUsRes.ProtoReflect.Descriptor instead.
func (*ContactUsRes) Descriptor() ([]byte, []int) {
	return file_forms_proto_rawDescGZIP(), []int{1}
}

type SafetyReportReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OccurredOn        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=occurred_on,json=occurredOn,proto3" json:"occurred_on,omitempty"`
	Description       string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Severity          int32                  `protobuf:"varint,3,opt,name=severity,proto3" json:"severity,omitempty"`
	IssuesBefore      bool                   `protobuf:"varint,4,opt,name=issues_before,json=issuesBefore,proto3" json:"issues_before,omitempty"`
	Resolution        string                 `protobuf:"bytes,5,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Name              string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Email             string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber       string                 `protobuf:"bytes,8,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	RecaptchaResponse string                 `protobuf:"bytes,9,opt,name=recaptcha_response,json=recaptchaResponse,proto3" json:"recaptcha_response,omitempty"`
}

func (x *SafetyReportReq) Reset() {
	*x = SafetyReportReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SafetyReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafetyReportReq) ProtoMessage() {}

func (x *SafetyReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_forms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafetyReportReq.ProtoReflect.Descriptor instead.
func (*SafetyReportReq) Descriptor() ([]byte, []int) {
	return file_forms_proto_rawDescGZIP(), []int{2}
}

func (x *SafetyReportReq) GetOccurredOn() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredOn
	}
	return nil
}

func (x *SafetyReportReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SafetyReportReq) GetSeverity() int32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *SafetyReportReq) GetIssuesBefore() bool {
	if x != nil {
		return x.IssuesBefore
	}
	return false
}

func (x *SafetyReportReq) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *SafetyReportReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SafetyReportReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SafetyReportReq) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *SafetyReportReq) GetRecaptchaResponse() string {
	if x != nil {
		return x.RecaptchaResponse
	}
	return ""
}

type SafetyReportRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SafetyReportRes) Reset() {
	*x = SafetyReportRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forms_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SafetyReportRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafetyReportRes) ProtoMessage() {}

func (x *SafetyReportRes) ProtoReflect() protoreflect.Message {
	mi := &file_forms_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafetyReportRes.ProtoReflect.Descriptor instead.
func (*SafetyReportRes) Descriptor() ([]byte, []int) {
	return file_forms_proto_rawDescGZIP(), []int{3}
}

var File_forms_proto protoreflect.FileDescriptor

var file_forms_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x64,
	0x73, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x79, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x55, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12,
	0x2d, 0x0a, 0x12, 0x72, 0x65, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x72, 0x65, 0x63,
	0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0e,
	0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x55, 0x73, 0x52, 0x65, 0x73, 0x22, 0xcd,
	0x02, 0x0a, 0x0f, 0x53, 0x61, 0x66, 0x65, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x3b, 0x0a, 0x0b, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0a, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x4f, 0x6e, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x12, 0x23, 0x0a,
	0x0d, 0x69, 0x73, 0x73, 0x75, 0x65, 0x73, 0x5f, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x73, 0x75, 0x65, 0x73, 0x42, 0x65, 0x66, 0x6f,
	0x72, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a, 0x0c,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x2d, 0x0a, 0x12, 0x72, 0x65, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x72, 0x65, 0x63,
	0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11,
	0x0a, 0x0f, 0x53, 0x61, 0x66, 0x65, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x73, 0x32, 0x76, 0x0a, 0x05, 0x46, 0x6f, 0x72, 0x6d, 0x73, 0x12, 0x31, 0x0a, 0x09, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x55, 0x73, 0x12, 0x11, 0x2e, 0x64, 0x73, 0x73, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x55, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x64, 0x73, 0x73,
	0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x55, 0x73, 0x52, 0x65, 0x73, 0x12, 0x3a, 0x0a,
	0x0c, 0x53, 0x61, 0x66, 0x65, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x2e,
	0x64, 0x73, 0x73, 0x2e, 0x53, 0x61, 0x66, 0x65, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x64, 0x73, 0x73, 0x2e, 0x53, 0x61, 0x66, 0x65, 0x74, 0x79,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x72, 0x70, 0x63,
	0x2f, 0x64, 0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_forms_proto_rawDescOnce sync.Once
	file_forms_proto_rawDescData = file_forms_proto_rawDesc
)

func file_forms_proto_rawDescGZIP() []byte {
	file_forms_proto_rawDescOnce.Do(func() {
		file_forms_proto_rawDescData = protoimpl.X.CompressGZIP(file_forms_proto_rawDescData)
	})
	return file_forms_proto_rawDescData
}

var file_forms_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_forms_proto_goTypes = []interface{}{
	(*ContactUsReq)(nil),          // 0: dss.ContactUsReq
	(*ContactUsRes)(nil),          // 1: dss.ContactUsRes
	(*SafetyReportReq)(nil),       // 2: dss.SafetyReportReq
	(*SafetyReportRes)(nil),       // 3: dss.SafetyReportRes
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_forms_proto_depIdxs = []int32{
	4, // 0: dss.SafetyReportReq.occurred_on:type_name -> google.protobuf.Timestamp
	0, // 1: dss.Forms.ContactUs:input_type -> dss.ContactUsReq
	2, // 2: dss.Forms.SafetyReport:input_type -> dss.SafetyReportReq
	1, // 3: dss.Forms.ContactUs:output_type -> dss.ContactUsRes
	3, // 4: dss.Forms.SafetyReport:output_type -> dss.SafetyReportRes
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_forms_proto_init() }
func file_forms_proto_init() {
	if File_forms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_forms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactUsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactUsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forms_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SafetyReportReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forms_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SafetyReportRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_forms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forms_proto_goTypes,
		DependencyIndexes: file_forms_proto_depIdxs,
		MessageInfos:      file_forms_proto_msgTypes,
	}.Build()
	File_forms_proto = out.File
	file_forms_proto_rawDesc = nil
	file_forms_proto_goTypes = nil
	file_forms_proto_depIdxs = nil
}
