// Code generated by protoc-gen-twirp v8.1.0, DO NOT EDIT.
// source: vaccine.proto

package dss

import context "context"
import fmt "fmt"
import http "net/http"
import ioutil "io/ioutil"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// =================
// Vaccine Interface
// =================

type Vaccine interface {
	Upload(context.Context, *VaccineUploadReq) (*VaccineUploadRes, error)

	Get(context.Context, *VaccineGetReq) (*VaccineGetRes, error)

	Approve(context.Context, *VaccineApproveReq) (*VaccineApproveRes, error)

	Reject(context.Context, *VaccineRejectReq) (*VaccineRejectRes, error)
}

// =======================
// Vaccine Protobuf Client
// =======================

type vaccineProtobufClient struct {
	client      HTTPClient
	urls        [4]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewVaccineProtobufClient creates a Protobuf client that implements the Vaccine interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewVaccineProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) Vaccine {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "dss", "Vaccine")
	urls := [4]string{
		serviceURL + "Upload",
		serviceURL + "Get",
		serviceURL + "Approve",
		serviceURL + "Reject",
	}

	return &vaccineProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *vaccineProtobufClient) Upload(ctx context.Context, in *VaccineUploadReq) (*VaccineUploadRes, error) {
	ctx = ctxsetters.WithPackageName(ctx, "dss")
	ctx = ctxsetters.WithServiceName(ctx, "Vaccine")
	ctx = ctxsetters.WithMethodName(ctx, "Upload")
	caller := c.callUpload
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *VaccineUploadReq) (*VaccineUploadRes, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*VaccineUploadReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*VaccineUploadReq) when calling interceptor")
					}
					return c.callUpload(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*VaccineUploadRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*VaccineUploadRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *vaccineProtobufClient) callUpload(ctx context.Context, in *VaccineUploadReq) (*VaccineUploadRes, error) {
	out := new(VaccineUploadRes)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *vaccineProtobufClient) Get(ctx context.Context, in *VaccineGetReq) (*VaccineGetRes, error) {
	ctx = ctxsetters.WithPackageName(ctx, "dss")
	ctx = ctxsetters.WithServiceName(ctx, "Vaccine")
	ctx = ctxsetters.WithMethodName(ctx, "Get")
	caller := c.callGet
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *VaccineGetReq) (*VaccineGetRes, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*VaccineGetReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*VaccineGetReq) when calling interceptor")
					}
					return c.callGet(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*VaccineGetRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*VaccineGetRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *vaccineProtobufClient) callGet(ctx context.Context, in *VaccineGetReq) (*VaccineGetRes, error) {
	out := new(VaccineGetRes)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *vaccineProtobufClient) Approve(ctx context.Context, in *VaccineApproveReq) (*VaccineApproveRes, error) {
	ctx = ctxsetters.WithPackageName(ctx, "dss")
	ctx = ctxsetters.WithServiceName(ctx, "Vaccine")
	ctx = ctxsetters.WithMethodName(ctx, "Approve")
	caller := c.callApprove
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *VaccineApproveReq) (*VaccineApproveRes, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*VaccineApproveReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*VaccineApproveReq) when calling interceptor")
					}
					return c.callApprove(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*VaccineApproveRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*VaccineApproveRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *vaccineProtobufClient) callApprove(ctx context.Context, in *VaccineApproveReq) (*VaccineApproveRes, error) {
	out := new(VaccineApproveRes)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *vaccineProtobufClient) Reject(ctx context.Context, in *VaccineRejectReq) (*VaccineRejectRes, error) {
	ctx = ctxsetters.WithPackageName(ctx, "dss")
	ctx = ctxsetters.WithServiceName(ctx, "Vaccine")
	ctx = ctxsetters.WithMethodName(ctx, "Reject")
	caller := c.callReject
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *VaccineRejectReq) (*VaccineRejectRes, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*VaccineRejectReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*VaccineRejectReq) when calling interceptor")
					}
					return c.callReject(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*VaccineRejectRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*VaccineRejectRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *vaccineProtobufClient) callReject(ctx context.Context, in *VaccineRejectReq) (*VaccineRejectRes, error) {
	out := new(VaccineRejectRes)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ===================
// Vaccine JSON Client
// ===================

type vaccineJSONClient struct {
	client      HTTPClient
	urls        [4]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewVaccineJSONClient creates a JSON client that implements the Vaccine interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewVaccineJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) Vaccine {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "dss", "Vaccine")
	urls := [4]string{
		serviceURL + "Upload",
		serviceURL + "Get",
		serviceURL + "Approve",
		serviceURL + "Reject",
	}

	return &vaccineJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *vaccineJSONClient) Upload(ctx context.Context, in *VaccineUploadReq) (*VaccineUploadRes, error) {
	ctx = ctxsetters.WithPackageName(ctx, "dss")
	ctx = ctxsetters.WithServiceName(ctx, "Vaccine")
	ctx = ctxsetters.WithMethodName(ctx, "Upload")
	caller := c.callUpload
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *VaccineUploadReq) (*VaccineUploadRes, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*VaccineUploadReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*VaccineUploadReq) when calling interceptor")
					}
					return c.callUpload(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*VaccineUploadRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*VaccineUploadRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *vaccineJSONClient) callUpload(ctx context.Context, in *VaccineUploadReq) (*VaccineUploadRes, error) {
	out := new(VaccineUploadRes)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *vaccineJSONClient) Get(ctx context.Context, in *VaccineGetReq) (*VaccineGetRes, error) {
	ctx = ctxsetters.WithPackageName(ctx, "dss")
	ctx = ctxsetters.WithServiceName(ctx, "Vaccine")
	ctx = ctxsetters.WithMethodName(ctx, "Get")
	caller := c.callGet
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *VaccineGetReq) (*VaccineGetRes, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*VaccineGetReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*VaccineGetReq) when calling interceptor")
					}
					return c.callGet(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*VaccineGetRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*VaccineGetRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *vaccineJSONClient) callGet(ctx context.Context, in *VaccineGetReq) (*VaccineGetRes, error) {
	out := new(VaccineGetRes)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *vaccineJSONClient) Approve(ctx context.Context, in *VaccineApproveReq) (*VaccineApproveRes, error) {
	ctx = ctxsetters.WithPackageName(ctx, "dss")
	ctx = ctxsetters.WithServiceName(ctx, "Vaccine")
	ctx = ctxsetters.WithMethodName(ctx, "Approve")
	caller := c.callApprove
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *VaccineApproveReq) (*VaccineApproveRes, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*VaccineApproveReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*VaccineApproveReq) when calling interceptor")
					}
					return c.callApprove(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*VaccineApproveRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*VaccineApproveRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *vaccineJSONClient) callApprove(ctx context.Context, in *VaccineApproveReq) (*VaccineApproveRes, error) {
	out := new(VaccineApproveRes)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *vaccineJSONClient) Reject(ctx context.Context, in *VaccineRejectReq) (*VaccineRejectRes, error) {
	ctx = ctxsetters.WithPackageName(ctx, "dss")
	ctx = ctxsetters.WithServiceName(ctx, "Vaccine")
	ctx = ctxsetters.WithMethodName(ctx, "Reject")
	caller := c.callReject
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *VaccineRejectReq) (*VaccineRejectRes, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*VaccineRejectReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*VaccineRejectReq) when calling interceptor")
					}
					return c.callReject(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*VaccineRejectRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*VaccineRejectRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *vaccineJSONClient) callReject(ctx context.Context, in *VaccineRejectReq) (*VaccineRejectRes, error) {
	out := new(VaccineRejectRes)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ======================
// Vaccine Server Handler
// ======================

type vaccineServer struct {
	Vaccine
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewVaccineServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewVaccineServer(svc Vaccine, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &vaccineServer{
		Vaccine:          svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *vaccineServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *vaccineServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// VaccinePathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const VaccinePathPrefix = "/twirp/dss.Vaccine/"

func (s *vaccineServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "dss")
	ctx = ctxsetters.WithServiceName(ctx, "Vaccine")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "dss.Vaccine" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "Upload":
		s.serveUpload(ctx, resp, req)
		return
	case "Get":
		s.serveGet(ctx, resp, req)
		return
	case "Approve":
		s.serveApprove(ctx, resp, req)
		return
	case "Reject":
		s.serveReject(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *vaccineServer) serveUpload(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveUploadJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveUploadProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *vaccineServer) serveUploadJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Upload")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(VaccineUploadReq)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.Vaccine.Upload
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *VaccineUploadReq) (*VaccineUploadRes, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*VaccineUploadReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*VaccineUploadReq) when calling interceptor")
					}
					return s.Vaccine.Upload(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*VaccineUploadRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*VaccineUploadRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *VaccineUploadRes
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *VaccineUploadRes and nil error while calling Upload. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *vaccineServer) serveUploadProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Upload")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(VaccineUploadReq)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.Vaccine.Upload
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *VaccineUploadReq) (*VaccineUploadRes, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*VaccineUploadReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*VaccineUploadReq) when calling interceptor")
					}
					return s.Vaccine.Upload(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*VaccineUploadRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*VaccineUploadRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *VaccineUploadRes
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *VaccineUploadRes and nil error while calling Upload. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *vaccineServer) serveGet(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *vaccineServer) serveGetJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Get")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(VaccineGetReq)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.Vaccine.Get
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *VaccineGetReq) (*VaccineGetRes, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*VaccineGetReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*VaccineGetReq) when calling interceptor")
					}
					return s.Vaccine.Get(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*VaccineGetRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*VaccineGetRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *VaccineGetRes
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *VaccineGetRes and nil error while calling Get. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *vaccineServer) serveGetProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Get")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(VaccineGetReq)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.Vaccine.Get
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *VaccineGetReq) (*VaccineGetRes, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*VaccineGetReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*VaccineGetReq) when calling interceptor")
					}
					return s.Vaccine.Get(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*VaccineGetRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*VaccineGetRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *VaccineGetRes
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *VaccineGetRes and nil error while calling Get. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *vaccineServer) serveApprove(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveApproveJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveApproveProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *vaccineServer) serveApproveJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Approve")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(VaccineApproveReq)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.Vaccine.Approve
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *VaccineApproveReq) (*VaccineApproveRes, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*VaccineApproveReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*VaccineApproveReq) when calling interceptor")
					}
					return s.Vaccine.Approve(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*VaccineApproveRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*VaccineApproveRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *VaccineApproveRes
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *VaccineApproveRes and nil error while calling Approve. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *vaccineServer) serveApproveProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Approve")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(VaccineApproveReq)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.Vaccine.Approve
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *VaccineApproveReq) (*VaccineApproveRes, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*VaccineApproveReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*VaccineApproveReq) when calling interceptor")
					}
					return s.Vaccine.Approve(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*VaccineApproveRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*VaccineApproveRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *VaccineApproveRes
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *VaccineApproveRes and nil error while calling Approve. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *vaccineServer) serveReject(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveRejectJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveRejectProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *vaccineServer) serveRejectJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Reject")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(VaccineRejectReq)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.Vaccine.Reject
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *VaccineRejectReq) (*VaccineRejectRes, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*VaccineRejectReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*VaccineRejectReq) when calling interceptor")
					}
					return s.Vaccine.Reject(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*VaccineRejectRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*VaccineRejectRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *VaccineRejectRes
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *VaccineRejectRes and nil error while calling Reject. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *vaccineServer) serveRejectProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Reject")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(VaccineRejectReq)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.Vaccine.Reject
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *VaccineRejectReq) (*VaccineRejectRes, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*VaccineRejectReq)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*VaccineRejectReq) when calling interceptor")
					}
					return s.Vaccine.Reject(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*VaccineRejectRes)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*VaccineRejectRes) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *VaccineRejectRes
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *VaccineRejectRes and nil error while calling Reject. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *vaccineServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor4, 0
}

func (s *vaccineServer) ProtocGenTwirpVersion() string {
	return "v8.1.0"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *vaccineServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "dss", "Vaccine")
}

var twirpFileDescriptor4 = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0x4d, 0xeb, 0xd3, 0x40,
	0x10, 0xc6, 0xff, 0x69, 0x24, 0xb5, 0x13, 0x2b, 0x75, 0x6c, 0x6b, 0xc9, 0xc5, 0xb2, 0x8a, 0xf4,
	0x62, 0x85, 0x8a, 0x82, 0x1e, 0x04, 0x7b, 0x69, 0x41, 0x91, 0x12, 0xb1, 0x07, 0x2f, 0x61, 0xcd,
	0x6e, 0x65, 0x25, 0x64, 0xd7, 0x4c, 0x1b, 0x8a, 0x5f, 0xd7, 0x93, 0xdf, 0x42, 0x92, 0x2c, 0x69,
	0x42, 0x72, 0xcb, 0x3c, 0x3b, 0x6f, 0xcf, 0x6f, 0xb3, 0x30, 0xce, 0x79, 0x1c, 0xab, 0x54, 0xae,
	0x4d, 0xa6, 0xcf, 0x1a, 0x5d, 0x41, 0xc4, 0xc6, 0xe0, 0x1f, 0xf9, 0xf5, 0xa3, 0x31, 0x99, 0xce,
	0xa5, 0x60, 0x2f, 0x00, 0xeb, 0x90, 0x27, 0x07, 0x99, 0x0a, 0x95, 0xfe, 0xc4, 0x09, 0xb8, 0x97,
	0x2c, 0x59, 0x38, 0x4b, 0x67, 0x35, 0x0a, 0x8b, 0x4f, 0x36, 0x05, 0xfc, 0xa2, 0x8f, 0xfc, 0x7a,
	0xc8, 0xb4, 0x3e, 0x7d, 0xbd, 0x18, 0x93, 0x28, 0x29, 0xd8, 0x07, 0x98, 0x1c, 0xab, 0x11, 0xdf,
	0x4c, 0xa2, 0xb9, 0x08, 0xe5, 0x6f, 0x7c, 0x08, 0x03, 0x25, 0x6c, 0xe9, 0x40, 0x09, 0x0c, 0xe0,
	0xfe, 0x49, 0x25, 0x92, 0xd4, 0x1f, 0xb9, 0x18, 0x2c, 0x9d, 0x95, 0x1b, 0xd6, 0x31, 0x7b, 0xde,
	0xa9, 0xa7, 0x9e, 0xd9, 0x4f, 0x61, 0x6c, 0xb3, 0x76, 0xf2, 0xdc, 0x33, 0x82, 0xfd, 0x73, 0xda,
	0x19, 0x84, 0x6f, 0xe0, 0x41, 0xce, 0xaf, 0x11, 0xb7, 0x36, 0xcb, 0x5c, 0x7f, 0x33, 0x59, 0x0b,
	0xa2, 0x75, 0xc3, 0xfe, 0xfe, 0x2e, 0xf4, 0xf3, 0x5b, 0x88, 0x9f, 0x60, 0x7a, 0x2b, 0xe3, 0x49,
	0x64, 0x2a, 0x1e, 0xe5, 0xde, 0xfe, 0xe6, 0x49, 0xbb, 0xbc, 0xc6, 0xb5, 0xbf, 0x0b, 0x31, 0xef,
	0x42, 0xfc, 0x0c, 0xb3, 0x54, 0x47, 0x45, 0x3f, 0x53, 0x40, 0x8b, 0xc8, 0x52, 0x5b, 0xb8, 0x8d,
	0x6e, 0x5d, 0xa8, 0x45, 0xb7, 0xb4, 0xa3, 0x6e, 0x3d, 0xb8, 0xa7, 0xd2, 0x93, 0x66, 0xcf, 0xe0,
	0x91, 0xb5, 0x6a, 0xb7, 0xee, 0x03, 0xf2, 0xb8, 0x9b, 0x44, 0xec, 0x7d, 0x0d, 0x3b, 0x94, 0xbf,
	0x64, 0xdc, 0x47, 0x12, 0xe7, 0xe0, 0x65, 0x92, 0x93, 0x4e, 0x4b, 0xcb, 0xa3, 0xd0, 0x46, 0x0c,
	0x3b, 0xb5, 0xb4, 0xf9, 0xeb, 0xc0, 0xd0, 0x8a, 0xf8, 0x16, 0xbc, 0xea, 0x06, 0x71, 0x66, 0x21,
	0xb5, 0xff, 0x8a, 0xa0, 0x57, 0x26, 0x7c, 0x09, 0xee, 0x4e, 0x9e, 0x11, 0x9b, 0xa7, 0xd5, 0x25,
	0x07, 0x5d, 0x8d, 0xf0, 0x1d, 0x0c, 0xad, 0x21, 0x9c, 0x37, 0x8f, 0x6f, 0x28, 0x82, 0x7e, 0x9d,
	0x8a, 0x0d, 0xab, 0xd5, 0xdb, 0x1b, 0xd6, 0x28, 0x82, 0x5e, 0x99, 0xb6, 0xa3, 0xef, 0xc3, 0xcc,
	0xc4, 0xaf, 0x04, 0xd1, 0x0f, 0xaf, 0x7c, 0x46, 0xaf, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x85,
	0x09, 0x54, 0xc8, 0x57, 0x03, 0x00, 0x00,
}
