version: 2.1
jobs:
  go-test:
    docker:
      # specify the version
      - image: circleci/golang:1.16
        environment:
          DSS_TEST_POSTGRESURL: postgres://root:password@localhost/circle_test?sslmode=disable
          GOPROXY: https://proxy.golang.org
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
    steps:
      - checkout

      - run:
          name: Install mage
          command: wget https://github.com/magefile/mage/releases/download/v1.11.0/mage_1.11.0_Linux-64bit.tar.gz -O - | tar xzf - -C /tmp

      - run: 
          name: Wait on DB
          command: |
            timeout 300 sh -c \
              'until nc -z localhost 5432; do
                 echo "Waiting for port ..."
                 sleep 1
               done'

      - run: 
          name: Perform DB Migrations
          command: MIGRATION_URL=$DSS_TEST_POSTGRESURL /tmp/mage -v migrate

      - run: 
          name: Perform tests
          command: cd dynamic && go test ./...
workflows:
  version: 2
  test:
    jobs:
      - go-test:
          filters:
            tags:
              only: /^v[0-9]\.[0-9]\.[0-9]$/
