version: 2.1
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.14
        environment:
          DSS_PG_URL: postgres://root:password@localhost/circle_test?sslmode=disable
          GOPROXY: https://proxy.golang.org
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - run:
          name: install tools
          command: go get github.com/Houndie/toolbox && toolbox sync

      - run: pwd

      - run:
          name: install migrate
          command: go get -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate/
          environment: 
            GOBIN: /home/circleci/project/_tools

      - run: 
          name: Wait on DB
          command: |
            timeout 300 sh -c \
              'until nc -z localhost 5432; do
                 echo "Waiting for port ..."
                 sleep 1
               done'

      - run: 
          name: Perform DB Migrations
          command: toolbox do -- migrate -path=dynamic/storage/postgres/migrations -database $DSS_PG_URL up

      - run: 
          name: Perform tests
          command: cd dynamic && go test ./...
