FROM postgres:12.3

RUN apt update && apt install -y curl 
RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.11.0/migrate.linux-amd64.tar.gz | tar xvz
COPY storage/postgres/migrations /migrations
COPY docker/migrate.sh /docker-entrypoint-initdb.d/migrate.sh
