# syntax=docker/dockerfile:1
FROM golang:1.16 AS builder

RUN mkdir /app
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o server ./cmd/server

FROM alpine:3.13.5 AS runner

RUN apk add --no-cache tzdata
COPY --from=builder /app/server .
COPY docker/startup.deploy.sh .
CMD ./startup.deploy.sh
