// Generated by protoc-gen-twirp_typescript. DO NOT EDIT
import {dss} from './health.pb';
import {createTwirpAdapter} from 'pbjs-twirp';
import Axios from 'axios';

const getServiceMethodName = (fn: any): string => {
	if (fn === dss.Info.prototype.health) {
		return 'Health';
    }
	if (fn === dss.Info.prototype.version) {
		return 'Version';
    }

    throw new Error('Unknown Method');
};


export const InfoPathPrefix = '/twirp/dss.Info/';

export const createInfo = (baseURL: string, options = {}): dss.Info => {
    const defaultOpts = {
        baseURL: baseURL + InfoPathPrefix,
        headers: {
          Accept: 'application/protobuf'
        }
    };
    const axiosOpts = { ...defaultOpts, ...options };
    
    const axios = Axios.create(axiosOpts);

    return dss.Info.create(createTwirpAdapter(axios, getServiceMethodName));
};
