// Generated by protoc-gen-twirp_typescript. DO NOT EDIT
import {dss} from './vaccine.pb';
import {createTwirpAdapter} from 'pbjs-twirp';
import Axios from 'axios';

const getServiceMethodName = (fn: any): string => {
	if (fn === dss.Vaccine.prototype.upload) {
		return 'Upload';
    }
	if (fn === dss.Vaccine.prototype.get) {
		return 'Get';
    }
	if (fn === dss.Vaccine.prototype.approve) {
		return 'Approve';
    }
	if (fn === dss.Vaccine.prototype.reject) {
		return 'Reject';
    }

    throw new Error('Unknown Method');
};


export const VaccinePathPrefix = '/twirp/dss.Vaccine/';

export const createVaccine = (baseURL: string, options = {}): dss.Vaccine => {
    const defaultOpts = {
        baseURL: baseURL + VaccinePathPrefix,
        headers: {
          Accept: 'application/protobuf'
        }
    };
    const axiosOpts = { ...defaultOpts, ...options };
    
    const axios = Axios.create(axiosOpts);

    return dss.Vaccine.create(createTwirpAdapter(axios, getServiceMethodName));
};
